name: Oglasi CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Preuzimanje projekta
        uses: actions/checkout@v4

      - name: Podesavanje Python-a
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalacija zavisnosti
        run: pip install -r requirements.txt

      - name: Provera aplikacije
        run: python -m py_compile app.py

      - name: Pokretanje testova
        run: python -m pytest

      - name: Discord - uspesan pipeline
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "embeds": [{
              "title": "🟢 Oglasi CI/CD - Deployment uspešan",
              "description": "Aplikacija je uspešno testirana i pipeline je završen.",
              "color": 3066993,
              "fields": [
                {
                  "name": "👤 Autor",
                  "value": "${{ github.actor }}",
                  "inline": true
                },
                {
                  "name": "📌 Commit",
                  "value": "`${{ github.sha }}`",
                  "inline": true
                },
                {
                  "name": "📊 Status",
                  "value": "SUCCESS",
                  "inline": true
                },
                {
                  "name": "🧪 Testovi",
                  "value": "2 testa uspešno prošla",
                  "inline": true
                },
                {
                  "name": "🔗 Logovi",
                  "value": "[Pogledaj GitHub Actions logove](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
                  "inline": false
                }
              ],
              "footer": {
                "text": "Oglasi Monitoring System"
              }
            }]
          }' \
          "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Discord - neuspesan pipeline
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"🔴 Oglasi CI/CD - pipeline je neuspešan!"}' \
          "${{ secrets.DISCORD_WEBHOOK }}"